- name: Generate unique identifier
  command: uuidgen
  register: identifier
- name: Configure GitHub Runner
  command: ./config.sh \
    --unattended \
    --url {{ github.org.url }} \
    --token {{ github.org.token }} \
    --name gh-runner-{{ identifier.stdout }}
    --labels {{ github.runner.os }},{{ github.runner.arch }}
  args:
    chdir: /opt/actions-runner
