- name: Ensure that GitHub Runner service was installed
  stat:
    path: /opt/actions-runner/.service
  register: service_file
- name: Installing GitHub Runner as a service
  when: not service_file.stat.exists
  command: ./svc.sh install
  become: yes
  args:
    chdir: /opt/actions-runner
- name: Locating GitHub Runner service
  command: cat .service
  register: service
  args:
    chdir: /opt/actions-runner
- name: Ensure GitHub Runner service has stated
  become: yes
  service:
    name: "{{ service.stdout }}"
    state: started
