- name: Configure GitHub Runner
  command: ./config.sh \
    --unattended \
    --url {{ github.org.url }} \
    --token {{ github.org.token }} \
    --name gh-runner-$RANDOM$RANDOM
    --labels {{ github.runner.os }},{{ github.runner.arch }}
  args:
    chdir: /opt/actions-runner

- name: Installing GitHub Runner as a service
  command: ./svc.sh install
  become: yes
  args:
    chdir: /opt/actions-runner
