- name: Ensure that GitHub runner archive was not downloaded
  stat:
    path: /opt/actions-runner.tar.gz
  register: archive
- name: Download the latest runner package
  when: not archive.stat.exists
  uri:
    url: https://github.com/actions/runner/releases/download/v{{ github.runner.version }}/actions-runner-{{ github.runner.os }}-{{ github.runner.arch }}-{{ github.runner.version }}.tar.gz
    dest: /opt/actions-runner.tar.gz
    follow_redirects: all
- name: Create a directory if it does not exist
  file:
    path: /opt/actions-runner/
    state: directory
    owner: github
    group: github
    mode: '0755'
- name: Extract the installer
  unarchive:
    src: /opt/actions-runner.tar.gz
    dest: /opt/actions-runner/
    remote_src: yes
- name: Fix /opt/actions-runner/ ownership
  file:
    path: /opt/actions-runner/
    state: directory
    owner: github
    group: github
    recurse: yes
