- name: Ensure that GitHub runner was not installed
  stat:
    path: /opt/actions-runner
  register: runner
- name: Downloading GitHub runner installer
  when: not runner.stat.exists
  import_tasks: download.yml

- name: Ensure that GitHub runner service was not installed
  stat:
    path: /opt/actions-runner/svc.sh
  register: svc
- name: Installing GitHub runner
  when: not svc.stat.exists
  import_tasks: configure.yml
