---
- name: Cleanup gradle cache
  hosts: all
  tasks:
    - name: Removing ~/.gradle directory
      ansible.builtin.file:
        path: "/home/{{ github_actions_runner_user }}/.gradle"
        state: absent

    # This directory is created by the "gradle/gradle-build-action" action
    - name: Removing "~/gradle-installations" directory
      ansible.builtin.file:
        path: "/home/{{ github_actions_runner_user }}/gradle-installations"
        state: absent
